NAME: 'BBN.cassava.cv1920.res50.100epoch'
OUTPUT_DIR: './output/cassava/cv1920'
SHOW_STEP: 100
SAVE_STEP: 5
VALID_STEP: 1
INPUT_SIZE: 512
COLOR_SPACE: 'RGB'
CPU_MODE: False

DATASET:
  DATASET: 'IMBALANCECASSAVA'
  IMBALANCECASSAVA:
    RATIO: 0.02

BACKBONE:
#  TYPE: 'bbn_res32_cifar'
  TYPE: 'bbn_res50'

MODULE:
  TYPE: 'GAP'

CLASSIFIER:
  TYPE: 'FC'
  BIAS: True

LOSS:
  LOSS_TYPE: 'CrossEntropy'

TRAIN:
  BATCH_SIZE: 16
  MAX_EPOCH: 100
  NUM_WORKERS: 8
  COMBINER:
    TYPE: 'bbn_mix'
#    TYPE: 'default'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.01
    MOMENTUM: 0.9
    WEIGHT_DECAY: 2e-4
  LR_SCHEDULER:
    TYPE: 'warmup'
    LR_STEP: [60, 80]
    LR_FACTOR: 0.1
    WARM_EPOCH: 5
  TENSORBOARD:
    ENABLE: True
  SAMPLER:
    TYPE: 'default'
    DUAL_SAMPLER:
      ENABLE: True
      TYPE: 'reverse'

#TRANSFORMS:
#  TRAIN_TRANSFORMS: ('random_crop', 'random_horizontal_flip')
#  TEST_TRANSFORMS: ()

TEST:
  BATCH_SIZE: 16
  NUM_WORKERS: 8
  MODEL_FILE: 'best_model.pth'

