NAME: 'BBN.cassava.cv1920.efficient-b4.100epoch'
OUTPUT_DIR: './output/cassava/cv1920'
SHOW_STEP: 50
SAVE_STEP: 5
VALID_STEP: 1
INPUT_SIZE: 512
COLOR_SPACE: 'RGB'
CPU_MODE: False

DATASET:
  DATASET: 'IMBALANCECASSAVA'
  IMBALANCECASSAVA:
    RATIO: 0.02

BACKBONE:
#  TYPE: 'bbn_res32_cifar'
#  TYPE: 'bbn_res50'
  TYPE: 'efficientnet-b4'
#  PRETRAINED_MODEL: "/workspace/BBN/cassava/pretrained_models/resnet50-19c8e357.pth"
  PRETRAINED_MODEL: "/workspace/BBN/cassava/pretrained_models/efficientnet-b4.pth"


MODULE:
  TYPE: 'GAP'

CLASSIFIER:
  TYPE: 'FC'
  BIAS: True

LOSS:
  LOSS_TYPE: 'CrossEntropy'

TRAIN:
  BATCH_SIZE: 32
  MAX_EPOCH: 100
  NUM_WORKERS: 16
  COMBINER:
    TYPE: 'bbn_mix'
#    TYPE: 'default'
  OPTIMIZER:
#    TYPE: 'SGD'
    TYPE: 'ADAM'
    BASE_LR: 0.0003
    MOMENTUM: 0.9
    WEIGHT_DECAY: 2e-4
  LR_SCHEDULER:
    TYPE: 'cosine'
    LR_STEP: [60, 80]
    LR_FACTOR: 0.1
    WARM_EPOCH: 5
  TENSORBOARD:
    ENABLE: True
  SAMPLER:
    TYPE: 'default'
#    TYPE: 'weighted sampler'
    DUAL_SAMPLER:
      ENABLE: True
      TYPE: 'reverse'
      #"balance"

#TRANSFORMS:
#  TRAIN_TRANSFORMS: ('random_crop', 'random_horizontal_flip')
#  TEST_TRANSFORMS: ()

TEST:
  BATCH_SIZE: 4
  NUM_WORKERS: 2
  MODEL_FILE: 'best_model.pth'

